name: Build Expo Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        # Added --force to ensure all peer deps like async-storage are installed
        run: npm install --legacy-peer-deps --force

      - name: Expo Prebuild
        run: npx expo prebuild --platform android --no-install --non-interactive

      - name: Bundle JavaScript
        run: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.ts \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res \
            --config metro.config.js

      - name: Fix Reanimated Node Path
        run: sudo ln -sf $(which node) /usr/local/bin/node

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: agon-preview-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
